### ISSUE TITLE
elasticsearch  安装失败了...

### ISSUE THREAD

**Issue by zhutf123** [ysc/word#1]
sudo ./plugin -t 1h -u http://apdplat.org/word/archive/v1.1.zip -i word
-> Installing word...
Trying http://apdplat.org/word/archive/v1.1.zip...
Downloading ......................................................................................................DONE
Installed word into /home/q/elasticsearch/elasticsearch-1.4.2/plugins/word

提示安装成功了, 但是 在es 启动的时候 没有家在任何的插件
[plugins                  ] [Silverclaw] loaded [], sites []

在我做分词测试的时候抛出异常
xxxxxxxx:9200/_analyze?analyzer=word&text=女士冲锋衣

org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer [word]
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:151)
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:60)
	at org.elasticsearch.action.support.single.custom.TransportSingleCustomOperationAction$AsyncSingleAction$1.run(TransportSingleCustomOperationAction.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by zhutf123** [comment]
补充一下.. es 的 版本 为 1.4.2

**Comment by ysc** [comment]
我测试了，可以的，你按如下命令再确认一下，elasticsearch1.4.2也可以：	
	1、打开命令行并切换到elasticsearch的bin目录
		cd elasticsearch-1.5.1/bin
	2、运行plugin脚本安装word分词插件：
		./plugin -u http://apdplat.org/word/archive/v1.2.zip -i word
	3、修改文件elasticsearch-1.5.1/config/elasticsearch.yml，新增如下配置：	
		index.analysis.analyzer.default.type : "word"
		index.analysis.tokenizer.default.type : "word"
	4、启动ElasticSearch测试效果，在Chrome浏览器中访问：	
		http://localhost:9200/_analyze?analyzer=word&text=杨尚川是APDPlat应用级产品开发平台的作者
