### ISSUE TITLE
1.3尝试对文本分词的过程中出现空指针

### ISSUE THREAD

**Issue by fat-bird** [ysc/word#28]
at org.apdplat.word.segmentation.impl.AbstractSegmentation.seg(AbstractSegmentation.java:151)
at org.apdplat.word.lucene.ChineseWordTokenizer.getWord(ChineseWordTokenizer.java:95)

方法 segSentence(final String sentence) 可能返回null，但调用的过程中忽略了处理

**Comment by ysc** [comment]
fixed: https://github.com/ysc/word/commit/55b40e59a67350b3c2d7a1d45875c2db31bae002
