### ISSUE TITLE
怎么自己用代码维护用户自定义词库？

### ISSUE THREAD

**Issue by orangesir** [ysc/word#51]
代码看了一圈，没有找到解决办法。
场景是这样的:词库是用的自己的数据库维护的而不是使用的文件,用户会通过借口动态更新词库,看了半天代码，始终没有找到可以自己通过代码自己添加单个词库的。
文档中支持:
指定方式有三种：
	指定方式一，编程指定（高优先级）：
		WordConfTools.set("dic.path", "classpath:dic.txt，d:/custom_dic");
		DictionaryFactory.reload();//更改词典路径之后，重新加载词典
	指定方式二，Java虚拟机启动参数（中优先级）：
		java -Ddic.path=classpath:dic.txt，d:/custom_dic
	指定方式三，配置文件指定（低优先级）：
		使用类路径下的文件word.local.conf来指定配置信息
		dic.path=classpath:dic.txt，d:/custom_dic
我想问一下可以代码只添加一个词么？

**Comment by ysc** [comment]
在程序中用代码维护词库, 方法如下:

    // 单个操作
    // 添加一个自定义词
    DictionaryFactory.getDictionary().add("杨尚川");
    // 删除一个自定义词
    DictionaryFactory.getDictionary().remove("刘诗诗");
    // 批量操作
    List<String> words = new ArrayList<>();
    words.add("刘德华");
    words.add("景甜");
    words.add("赵丽颖");
    // 添加一批自定义词
    DictionaryFactory.getDictionary().addAll(words);
    // 删除一批自定义词
    DictionaryFactory.getDictionary().removeAll(words);

**Comment by ysc** [comment]
如果你有多个分词器，则可用如下方式，用
 https://github.com/ysc/word_web 这个项目来维护词库。

分布式中文分词器

	1、在自定义配置文件word.conf或word.local.conf中指定所有的配置项*.path使用HTTP资源，同时指定配置项redis.*

        #词典
        dic.path=http://localhost:8080/word_web/resources/dic.txt
        #词性标注数据
        part.of.speech.dic.path=http://localhost:8080/word_web/resources/part_of_speech_dic.txt
        #词性说明数据
        part.of.speech.des.path=http://localhost:8080/word_web/resources/part_of_speech_des.txt
        #二元模型
        bigram.path=http://localhost:8080/word_web/resources/bigram.txt
        #三元模型
        trigram.path=http://localhost:8080/word_web/resources/trigram.txt
        #停用词词典
        stopwords.path=http://localhost:8080/word_web/resources/stopwords.txt
        #用于分割词的标点符号
        punctuation.path=http://localhost:8080/word_web/resources/punctuation.txt
        #百家姓
        surname.path=http://localhost:8080/word_web/resources/surname.txt
        #数量词
        quantifier.path=http://localhost:8080/word_web/resources/quantifier.txt

        #redis服务，用于实时检测HTTP资源变更
        #redis主机
        redis.host=localhost
        #redis端口
        redis.port=6379

	2、配置并启动redis服务器

	    所有的分词器都会订阅redis服务器, 当redis服务器收到用户对资源的新增或删除指令后, 会通知所有的分词器进行相应的操作

	3、配置并启动提供HTTP资源的web服务器，即将项目：https://github.com/ysc/word_web 部署到tomcat的8080端口

        // 通知所有的分词器增加"杨尚川"这个词
        http://localhost:8080/word_web/admin/dic.jsp?action=add&dic=杨尚川
        // 通知所有的分词器删除"笔记本"这个词
        http://localhost:8080/word_web/admin/dic.jsp?action=remove&dic=笔记本

        dic.jsp收到用户的请求后会将消息投递到redis服务器, redis服务器在发布消息给所有订阅的分词器

**Comment by orangesir** [comment]
佩服，佩服。仔细看了部分代码，代码写的很漂亮！

**Comment by Phoenixinfire** [comment]
这个代码维护的功能addAll报错，Exception in thread "main" java.lang.RuntimeException: addAll method can just be used once after clear method!
	at org.apdplat.word.dictionary.impl.DoubleArrayDictionaryTrie.addAll(DoubleArrayDictionaryTrie.java:253)
能帮忙分析一下吗？

**Comment by weimo123** [comment]
> 这个代码维护的功能addAll报错，Exception in thread "main" java.lang.RuntimeException: addAll method can just be used once after clear method!
> at org.apdplat.word.dictionary.impl.DoubleArrayDictionaryTrie.addAll(DoubleArrayDictionaryTrie.java:253)
> 能帮忙分析一下吗？

我也遇到这个问题了

**Comment by Volong** [comment]
> > 这个代码维护的功能addAll报错，Exception in thread "main" java.lang.RuntimeException: addAll method can just be used once after clear method!
> > at org.apdplat.word.dictionary.impl.DoubleArrayDictionaryTrie.addAll(DoubleArrayDictionaryTrie.java:253)
> > 能帮忙分析一下吗？
> 
> 我也遇到这个问题了

报错信息不是很明显了吗

**Comment by 2011cine** [comment]
DictionaryFactory.getDictionary().clear();
DictionaryFactory.getDictionary().addAll(musicDictWords);
添加后，词典完全不起作用。。网上也有人请教了，仿佛你都没有回答。。

https://www.oschina.net/question/3374994_2235415

**Comment by Volong** [comment]
@2011cine 用的是什么分词算法？添加的什么词没有效果？

**Comment by 2011cine** [comment]
> @2011cine 用的是什么分词算法？添加的什么词没有效果？
用的默认分词算法，这个问题解决了，我发现reload()后会没有效果。
但是遇到一个新问题，就是我这个词库是专门针对音乐的，也就是说，加个这个词库，其他的默认词库都不生效了，我要向识别其他词还得调两次分词结果：一次是我专门的词库一个结果 另外一次是默认的。

有没有办法让默认的词库和我添加的词库同时生效@Volong

**Comment by Volong** [comment]
@2011cine 不知道你是怎么做的，所以没办法定位问题。
我目前的做法是使用第三种方式来指定自定义词库的。
