### ISSUE TITLE
对文件进行分词 计算分词速度 java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by julyking0** [ysc/word#68]
报错信息：
java.lang.ArithmeticException: / by zero
	at org.apdplat.word.util.Utils.seg(Utils.java:156) ~[word-1.3.jar:na]
	at org.apdplat.word.WordFrequencyStatistics.seg(WordFrequencyStatistics.java:155) ~[word-1.3.jar:na]
代码位置：
![image](https://user-images.githubusercontent.com/33617310/41970306-ebf606c6-7a3c-11e8-840e-cf87e4522553.png)

org.apdplat.word.util.Utils#seg(java.io.File, java.io.File, boolean, org.apdplat.word.segmentation.SegmentationAlgorithm, org.apdplat.word.util.Utils.FileSegmentationCallback)

**Comment by yjy123123** [comment]
请问这个报错该怎么解决呢？

**Comment by BoshCHEN** [comment]
请问解决了吗
