### ISSUE TITLE
Solr 5.4.0 无法加载 word 分词插件

### ISSUE THREAD

**Issue by glacjay** [ysc/word#7]
看错误日志大概是因为没有实现该版本的一个（些）接口。

注：word-1.3.1 版出现此错误，而 word-1.3 版无此错误。

相关错误日志如下：

```
2016-01-04 01:33:48.281 ERROR (qtp859417998-20) [   x:inverst] o.a.s.s.HttpSolrCall null:java.lang.RuntimeException: java.lang.AbstractMethodError: org.apache.lucene.analysis.util.TokenizerFactory.create(Lorg/apache/lucene/util/AttributeFactory;)Lorg/apache/lucene/analysis/Tokenizer;
	at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:611)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:472)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:222)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:181)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: org.apache.lucene.analysis.util.TokenizerFactory.create(Lorg/apache/lucene/util/AttributeFactory;)Lorg/apache/lucene/analysis/Tokenizer;
	at org.apache.lucene.analysis.util.TokenizerFactory.create(TokenizerFactory.java:75)
	at org.apache.solr.analysis.TokenizerChain.createComponents(TokenizerChain.java:89)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:176)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:205)
	at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:373)
	at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:753)
	at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:548)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:315)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:186)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:154)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:160)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:247)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:156)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2073)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:658)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:457)
	... 22 more

2016-01-04 01:33:48.283 WARN  (qtp859417998-20) [   x:inverst] o.e.j.s.ServletHandler Error for /solr/inverst/select
java.lang.AbstractMethodError: org.apache.lucene.analysis.util.TokenizerFactory.create(Lorg/apache/lucene/util/AttributeFactory;)Lorg/apache/lucene/analysis/Tokenizer;
	at org.apache.lucene.analysis.util.TokenizerFactory.create(TokenizerFactory.java:75)
	at org.apache.solr.analysis.TokenizerChain.createComponents(TokenizerChain.java:89)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:101)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:176)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:205)
	at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:373)
	at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:753)
	at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:548)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:315)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:186)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:154)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:160)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:247)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:156)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2073)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:658)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:457)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:222)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:181)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ysc** [comment]
word 1.3.1这个版本是从代码分支ForElasticsearch1.7.2中编译出来的，主要目的是支持 与lucene4.10.4、solr4.10.4和elasticsearch1.7.2兼容的版本。

**Comment by glacjay** [comment]
那这个版本号定的不是太好，因为一般都会认为 1.3.1 是 1.3 的兼容升级版。

**Comment by glacjay** [comment]
那这个版本号定的不是太好，因为一般都会认为 1.3.1 是 1.3 的兼容升级版。
