### ISSUE TITLE
在 Elasticsearch 7.4.2 中安装后，启动报错

### ISSUE THREAD

**Issue by Alistair-zhong** [ysc/word#86]
**错误日志如下**

```
{"type": "server", "timestamp": "2021-01-11T01:32:38,874Z", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "es-cluster", "node.name": "elasticsearch", "message": "uncaught exception in thread [main]",

"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site, isolated]",

"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.4.2.jar:7.4.2]",

"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.4.2.jar:7.4.2]",

"Caused by: java.lang.IllegalArgumentException: Unknown properties in plugin descriptor: [jvm, site, isolated]",

"at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:233) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:398) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:386) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:379) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:151) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.2.jar:7.4.2]",

"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.2.jar:7.4.2]",

"... 6 more"] }
```

**我的安装步骤**

  1. wget http://apdplat.org/word/archive/v1.4.1.zip
  2. mkdir plugins/word
  3. unzip -d plugins/word v1.4.1.zip
  4. plugins/word/plugin-descriptor.properties 文件中的elasticsearch.version 改为 7.4.2
  5. 重启 docker 中的 elasticsearch
  6. 然后就报错了.....

希望谁能帮助一下，是漏什么操作了还是有的地方我整错了？ Thx

**Comment by Alistair-zhong** [comment]
### 解决办法

  将 `plugins/word/plugin-descriptor.properties` 文件中的 `jvm`, `site`,` isolated` 三个参数用 # 号注释即可

```
#isolated=true
#site=false
#jvm=true
```
